language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
 - npm install -D # 安装构建阿奇依赖
 - cd ./test/smoke/template
 - npm install -D # 安装模板项目依赖

script:
  - npm test
